classify_ticket_type_task:
  description: >
    Set a ticket type for the ticket by choosing one of the following options: {ticket_types}
  expected_output: >
    Only the chosen ticket type.
  agent: ticket_classifier

classify_ticket_priority_task:
  description: >
    Set a ticket priority for the ticket by choosing one of the following options: {ticket_priorities}
  expected_output: >
    Only the chosen ticket priority.
  agent: ticket_classifier

classify_ticket_sentiment_task:
  description: >
    Determine the ticket publisher's sentiment by choosing one of the following options: {ticket_sentiments}
  expected_output: >
    Only the chosen ticket sentiment.
  agent: ticket_classifier

classify_ticket_tags_task:
  description: >
    Assign ticket tags (minimum = 1 tag, maximum = 3 tags) by choosing from the following options: {ticket_tags}
  expected_output: >
    Only the chosen ticket tags as list.
  agent: ticket_classifier

classify_responsible_team_task:
  description: >
    Assign a responsible team to the ticket by choosing one of the following options: {responsible_teams}
  expected_output: >
    Only the chosen responsible team.
  agent: ticket_classifier
  context:
    - classify_ticket_tags_task

key_words_extraction_task:
  description: >
    Extract key words that could be helpful for ticket resolution. Keep it very brief. Maximum 500 characters. Provide in german language.
  expected_output: >
    Only the extracted key words as list.
  agent: ticket_classifier

initial_action_suggestion_task:
  description: >
    Suggest an initial action for handling the ticket. Provide a brief explanation (1-15 sentences). Maximum 5000 characters. Provide in german language.
  expected_output: >
    Only the suggested initial action with brief explanation.
  agent: ticket_classifier

confidence_score_task:
  description: >
    Provide a confidence score for your classification (between 0.0 and 1.0).
    If you're unsure about any aspect of your classification tasks, reflect that in your confidence score.
  expected_output: >
    Only the confidence score as float.
  agent: ticket_classifier

reasoning_task:
  description: >
    Provide reasoning for your classification steps. Provide a brief explanation (1-10 sentences). Maximum 2000 characters. Provide in german language.
  expected_output: >
    Only the reasoning as text.
  agent: ticket_classifier
  context:
    - classify_ticket_type_task
    - classify_ticket_priority_task
    - classify_ticket_sentiment_task
    - classify_ticket_tags_task
    - classify_responsible_team_task